In [24]:
from skimage.transform import resize
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

print(1)

1


In [25]:
im = Image.open('./test/xx.png')
im_np = np.array(im)
print(im_np)

im = Image.fromarray(im_np)
im.show()
im_np_resize = resize(im_np, (140, 54))
print(im_np_resize)
plt.imshow(im_np_resize)


[[[ 20  20  20]
  [ 20  19  11]
  [ 17  15   2]
  ...
  [ 15  15  15]
  [ 16  16  16]
  [ 15  15  15]]

 [[ 15  23  16]
  [ 19  19  19]
  [ 20  19  10]
  ...
  [ 17  15   2]
  [ 17  15   2]
  [ 10  10  10]]

 [[ 17  15   2]
  [ 18  16   3]
  [ 17  15   2]
  ...
  [ 15  15  15]
  [ 15  15  15]
  [ 14  23  15]]

 ...

 [[169 139  95]
  [148 120  81]
  [150 124  79]
  ...
  [219 191 122]
  [219 192 123]
  [219 192 123]]

 [[153 121  77]
  [143 117  68]
  [163 138  84]
  ...
  [214 186 114]
  [214 186 111]
  [212 184 106]]

 [[147 121  70]
  [170 143  86]
  [177 150  97]
  ...
  [221 193 119]
  [220 192 107]
  [199 173  90]]]
